smart_content_cdn.config:
  type: config_object
  label: 'Smart Content CDN config'
  mapping:
    set_vary:
      label: 'Set Vary header'
      type: boolean
    geo_default:
      label: 'Default Geo value'
      type: string
